# Generated by penv 1.0.0-test from .env.schema. Do not edit.

from __future__ import annotations

import os
from typing import Any, Callable, Literal

from pydantic import HttpUrl, SecretStr


def _require(name: str) -> str:
    value = os.environ.get(name)
    if value is None or value == "":
        raise RuntimeError(f"{name} is not set; run penv check")
    return value


def _maybe(cast: Callable[[str], Any], name: str, default: str | None) -> Any:
    value = os.environ.get(name)
    if value is None or value == "":
        value = default
    return None if value is None else cast(value)


def _flag(raw: str) -> bool:
    return raw.strip().lower() in ("1", "true", "yes", "on")


class Env:
    def __init__(self) -> None:
        # Where the service keeps its own rows.
        self.DATABASE_URL: SecretStr = SecretStr(_require("DATABASE_URL"))
        self.STRIPE_SECRET_KEY: SecretStr = SecretStr(_require("STRIPE_SECRET_KEY"))
        # Where the browser is sent back to after a redirect.
        self.NEXT_PUBLIC_APP_URL: HttpUrl | None = _maybe(HttpUrl, "NEXT_PUBLIC_APP_URL", "http://localhost:3000")
        self.PORT: int | None = _maybe(int, "PORT", "3000")
        self.NODE_ENV: Literal["development", "staging", "production"] | None = _maybe(str, "NODE_ENV", "development")
        # The tier this deployment serves.
        self.PLAN_TIER: Literal["free", "pro", "enterprise"] = _require("PLAN_TIER")
        # How long a cached value stays fresh.
        self.CACHE_TTL_SECONDS: float | None = _maybe(float, "CACHE_TTL_SECONDS", "1.5")
        self.MAX_RETRIES: int = int(_require("MAX_RETRIES"))
        self.FEATURE_BILLING: bool | None = _maybe(_flag, "FEATURE_BILLING", "false")
        self.DEBUG_TRACING: bool = _flag(_require("DEBUG_TRACING"))
        # Where failures are mailed.
        self.ALERTS_EMAIL: str | None = _maybe(str, "ALERTS_EMAIL", "ops@example.test")
        self.SUPPORT_NOTE: SecretStr | None = _maybe(SecretStr, "SUPPORT_NOTE", None)


env = Env()