// Generated by penv 1.0.0-test from .env.schema. Do not edit.

export const env = {
  /** Where the service keeps its own rows. */
  DATABASE_URL: process.env.DATABASE_URL as string,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY as string,
  /** Where the browser is sent back to after a redirect. */
  NEXT_PUBLIC_APP_URL: (process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000") as string,
  PORT: Number(process.env.PORT ?? "3000"),
  NODE_ENV: (process.env.NODE_ENV ?? "development") as "development" | "staging" | "production",
  /** The tier this deployment serves. */
  PLAN_TIER: process.env.PLAN_TIER as "free" | "pro" | "enterprise",
  /** How long a cached value stays fresh. */
  CACHE_TTL_SECONDS: Number(process.env.CACHE_TTL_SECONDS ?? "1.5"),
  MAX_RETRIES: Number(process.env.MAX_RETRIES),
  FEATURE_BILLING: (process.env.FEATURE_BILLING ?? "false") === "true",
  DEBUG_TRACING: process.env.DEBUG_TRACING === "true",
  /** Where failures are mailed. */
  ALERTS_EMAIL: (process.env.ALERTS_EMAIL ?? "ops@example.test") as string,
  SUPPORT_NOTE: process.env.SUPPORT_NOTE as string | undefined,
} as const;

export type Env = typeof env;

export const envSchema = {
  "~standard": {
    version: 1,
    vendor: "penv",
    validate: (value: unknown) => {
      const seen = (value ?? {}) as Record<string, unknown>;
      const issues: { message: string; path: [string] }[] = [];
      if (seen["DATABASE_URL"] === undefined || seen["DATABASE_URL"] === "") {
        issues.push({ message: "DATABASE_URL is required", path: ["DATABASE_URL"] });
      }
      if (seen["STRIPE_SECRET_KEY"] === undefined || seen["STRIPE_SECRET_KEY"] === "") {
        issues.push({ message: "STRIPE_SECRET_KEY is required", path: ["STRIPE_SECRET_KEY"] });
      }
      if (seen["NODE_ENV"] !== undefined && !["development","staging","production"].includes(seen["NODE_ENV"] as string)) {
        issues.push({ message: "NODE_ENV must be one of development, staging, production", path: ["NODE_ENV"] });
      }
      if (seen["PLAN_TIER"] === undefined || seen["PLAN_TIER"] === "") {
        issues.push({ message: "PLAN_TIER is required", path: ["PLAN_TIER"] });
      }
      if (seen["PLAN_TIER"] !== undefined && !["free","pro","enterprise"].includes(seen["PLAN_TIER"] as string)) {
        issues.push({ message: "PLAN_TIER must be one of free, pro, enterprise", path: ["PLAN_TIER"] });
      }
      if (seen["MAX_RETRIES"] === undefined || seen["MAX_RETRIES"] === "") {
        issues.push({ message: "MAX_RETRIES is required", path: ["MAX_RETRIES"] });
      }
      if (seen["DEBUG_TRACING"] === undefined || seen["DEBUG_TRACING"] === "") {
        issues.push({ message: "DEBUG_TRACING is required", path: ["DEBUG_TRACING"] });
      }
      return issues.length > 0 ? { issues } : { value: seen as unknown as Env };
    },
  },
} as const;